repos:
  - repo: local
    hooks:
      - id: docker-compose-check
        name: Validate Docker Compose
        entry: docker compose config
        language: system
        files: ^docker-compose\.ya?ml$
        pass_filenames: false

      - id: secret-grabber
        name: Check for Hardcoded Secrets (Trivy)
        # Ищем секреты силами Trivy
        entry: trivy fs --scanners secret --exit-code 1 .
        language: system
        pass_filenames: false
