name: Ci

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  devsecops_pipeline:
    runs-on: ubuntu-latest

    steps:
      # Этот экшен базовый
      - name: Клонируем репозиторий
        uses: actions/checkout@v4

      # 1. Запуск GitLeaks через официальный Docker-образ
      - name: Запуск GitLeaks (Поиск секретов)
        run: |
          docker run --rm -v $(pwd):/path zricethezav/gitleaks:latest detect --verbose --source /path
        continue-on-error: false

      # 2. Запуск Trivy через официальный Docker-образ
      - name: Запуск Trivy Config Scan
        run: |
          docker run --rm -v $(pwd):/apps -w /apps aquasec/trivy:latest config --severity HIGH,CRITICAL --exit-code 1 .
        continue-on-error: false

      # 3. Валидация k8s манифестов через Kube-score
      - name: Запуск Kube-score (Линтер манифестов)
        run: |
          docker run --rm -v $(pwd):/project -w /project zegl/kube-score:latest score *.yaml
        continue-on-error: false

      # 4. Уведомление в Telegram при УСПЕШНОМ прохождении
      - name: Уведомление в Telegram (Успех)
        if: success()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -X POST "https://telegram.org{TELEGRAM_TOKEN}/sendMessage" \
          -d "chat_id=${TELEGRAM_CHAT_ID}" \
          -d "text=✅ Пайплайн проекта k3s-infra-test успешно пройден!%0AКоммит: ${{ github.event.head_commit.message }}"

      # 5. Уведомление в Telegram при ПАДЕНИИ
      - name: Уведомление в Telegram (Ошибка)
        if: failure()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -X POST "https://telegram.org{TELEGRAM_TOKEN}/sendMessage" \
          -d "chat_id=${TELEGRAM_CHAT_ID}" \
          -d "text=❌ Пайплайн проекта k3s-infra-test завален!%0AПроверьте логи сборки безопасности в GitVerse.%0AАвтор коммита: ${{ github.actor }}"














