name: Simple Ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # ШАГ 1: Автоматическая сборка безопасного Docker-образа в облаке
  build-ci-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Логинимся в Container Registry от GitVerse (используем встроенный токен пайплайна)
      - name: Log in to GitVerse Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.gitverse.ru
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Собираем наш мультистейдж Dockerfile и пушим его с тегом latest
      - name: Build and push DevOps Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.gitverse.ru/${{ github.repository }}/devops-ci:latest

  # ШАГ 2: Запуск тестов безопасности и валидации ВНУТРИ нашего нового образа
  validate:
    needs: build-ci-image # Ждем, пока соберется и запушится образ из первого шага
    runs-on: ubuntu-latest
    # Заставляем весь джоб крутиться внутри нашего собственного собранного контейнера
    container:
      image: registry.gitverse.ru/${{ github.repository }}/devops-ci:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Все сканеры уже лежат внутри образа, запускаем их напрямую без wget/curl за 0 секунд!
      - name: Run Gitleaks (Secret Scanner)
        run: gitleaks detect --verbose --redact

      - name: Run Trivy vulnerability scanner (IaC)
        run: trivy config --exit-code 1 --severity CRITICAL,HIGH .

      - name: Run YAMLLint
        run: yamllint .

      - name: Validate apps manifests via Kubeconform
        run: kubeconform -summary -strict apps/





