name: Security Scan

on:
  push:
    branches: [ master, main ]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy CLI
        run: |
          echo "Скачиваем и устанавливаем Trivy CLI..."
          curl -sfL https://githubusercontent.com | sh -s -- -b /usr/local/bin v0.50.0

      - name: Run Trivy Scan
        run: |
          echo "Запуск сканирования конфигураций..."
          /usr/local/bin/trivy config .
