services:
  # Первый балансировщик (Приоритет выше -> станет MASTER)
  haproxy-1:
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    container_name: haproxy-1
    restart: always
    # Запрашиваем у ядра Linux только точечные сетевые привилегии
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - KEEPALIVED_PRIORITY=101
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "6443:6443" # Проброс основного порта на хост
    networks:
      k3s-net:
        ipv4_address: 172.20.0.100

  # Второй балансировщик (Приоритет ниже -> станет BACKUP)
  haproxy-2:
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    container_name: haproxy-2
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - KEEPALIVED_PRIORITY=100
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "6444:6443" # Резервный порт на хосте на случай тестов напрямую
    networks:
      k3s-net:
        ipv4_address: 172.20.0.101

  # Инициализатор кластера (Лидер Raft)
  k3s-master-1:
    image: rancher/k3s:v1.31.1-k3s1
    container_name: k3s-master-1
    privileged: true
    restart: always
    environment:
      - K3S_TOKEN=SECRET_CLUSTER_TOKEN
    command: >
      server 
      --cluster-init
      --tls-san=172.20.0.10
      --tls-san=localhost
    volumes:
      - k3s-master-1-data:/var/lib/rancher/k3s
    networks:
      k3s-net:
        ipv4_address: 172.20.0.11

  # Второй мастер (Участник кворума)
  k3s-master-2:
    image: rancher/k3s:v1.31.1-k3s1
    container_name: k3s-master-2
    privileged: true
    restart: always
    depends_on:
      - k3s-master-1
    environment:
      - K3S_TOKEN=SECRET_CLUSTER_TOKEN
    command: >
      server 
      --server https://172.20.0.11:6443
      --tls-san=172.20.0.10
      --tls-san=localhost
    volumes:
      - k3s-master-2-data:/var/lib/rancher/k3s
    networks:
      k3s-net:
        ipv4_address: 172.20.0.12

  # Третий мастер (Для нечетного кворума)
  k3s-master-3:
    image: rancher/k3s:v1.31.1-k3s1
    container_name: k3s-master-3
    privileged: true
    restart: always
    depends_on:
      - k3s-master-1
    environment:
      - K3S_TOKEN=SECRET_CLUSTER_TOKEN
    command: >
      server 
      --server https://172.20.0.11:6443
      --tls-san=172.20.0.10
      --tls-san=localhost
    volumes:
      - k3s-master-3-data:/var/lib/rancher/k3s
    networks:
      k3s-net:
        ipv4_address: 172.20.0.13

volumes:
  k3s-master-1-data:
  k3s-master-2-data:
  k3s-master-3-data:

networks:
  k3s-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16



