---
- name: Создаем изолированную директорию для конфигов внутри проекта
  ansible.builtin.file:
    path: "{{ playbook_dir }}/.kube"
    state: directory
    mode: '0700'
  delegate_to: localhost
  run_once: true

- name: Читаем оригинальный kubeconfig с удаленного мастера K3s
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: remote_kubeconfig
  run_once: true
  become: true

- name: Сохраняем kubeconfig в локальную папку проекта
  ansible.builtin.copy:
    content: "{{ remote_kubeconfig['content'] | b64decode }}"
    dest: "{{ playbook_dir }}/.kube/config"
    mode: '0600'
  delegate_to: localhost
  run_once: true






