---
# ==============================================================================
# ДЕПЛОЙ ИНФРАСТРУКТУРЫ МОНИТОРИНГА И ПРИЛОЖЕНИЙ (Изолированная Версия)
# ==============================================================================

- name: Создаем пространство имен monitoring для стека мониторинга
  kubernetes.core.k8s:
    kubeconfig: "{{ playbook_dir }}/.kube/config"
    context: default
    name: monitoring
    kind: Namespace
    state: present
  register: ns_creation
  until: ns_creation is success
  retries: 10
  delay: 5

- name: Создаем Kubernetes секрет с паролем от Grafana из Ansible Vault
  kubernetes.core.k8s:
    kubeconfig: "{{ playbook_dir }}/.kube/config"
    context: default
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: grafana-admin-credentials
        namespace: monitoring
      type: Opaque
      stringData:
        admin-user: "{{ vault_grafana_admin_user }}"
        admin-password: "{{ vault_grafana_admin_password }}"
  register: secret_creation
  until: secret_creation is success
  retries: 10
  delay: 5

- name: Добавляем Helm-репозитории для Grafana и Prometheus COMMUNITY
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
    force_update: true # <--- Вставляем сюда. Ansible сам обновит кэш для grafana и prometheus
  loop:
    - { name: 'grafana', url: 'https://grafana.github.io/helm-charts' }
    - { name: 'prometheus-community', url: 'https://prometheus-community.github.io/helm-charts' }

- name: Устанавливаем Grafana Loki (Сбор логов)
  kubernetes.core.helm:
    kubeconfig: "{{ playbook_dir }}/.kube/config"
    context: default
    name: loki
    chart_ref: grafana/loki
    release_namespace: monitoring
    timeout: 3m
    values_files:
      - "{{ loki_values_path }}"
    state: present
    atomic: true
  register: helm_loki_res
  until: helm_loki_res is success
  retries: 5
  delay: 10

- name: Устанавливаем Prometheus Operator + Grafana (Сбор метрик)
  kubernetes.core.helm:
    kubeconfig: "{{ playbook_dir }}/.kube/config"
    context: default
    name: kube-prom
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    timeout: 3m
    values_files:
      - "{{ mon_values_path }}"
    state: present
    atomic: true
  register: helm_prom_res
  until: helm_prom_res is success
  retries: 5
  delay: 10

- name: Разворачиваем целевое веб-приложение Nginx
  kubernetes.core.k8s:
    kubeconfig: "{{ playbook_dir }}/.kube/config"
    context: default
    state: present
    # Вместо одного файла указываем путь к нашей новой директории с манифестами
    src: "{{ playbook_dir }}/k8s/apps/nginx/"






