---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-init-html
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  index.html: |
    {{- .Files.Get "files/index.html" | nindent 4 }}
