---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
