[k3s_masters]
k3s-master-1
k3s-master-2
k3s-master-3

[loadbalancers]
haproxy-1 ansible_host=172.20.0.100 keepalived_role=MASTER keepalived_priority=101 ansible_docker_user=root ansible_remote_tmp=/tmp
haproxy-2 ansible_host=172.20.0.101 keepalived_role=BACKUP keepalived_priority=100 ansible_docker_user=root ansible_remote_tmp=/tmp

[all:vars]
# Указываем Ansible подключаться через Docker API вместо SSH
ansible_connection=docker
# Отключаем поиск Python-интерпретатора, так как в rancher/k3s используется встроенный бинарник
ansible_python_interpreter=/bin/sh

# Настройки отказоустойчивого VIP
cluster_vip=172.20.0.10
vip_interface=eth0
