- name: Развертывание k3s локально и настройка окружения
  hosts: k3s_nodes
  gather_facts: true # для сбора системных переменных

  tasks:
    - name: Вывод имени текущего пользователя (для теста)
      debug:
        msg: "Привет, я запустился от имени пользователя {{ ansible_user_id }}, его dir: {{ ansible_user_dir }}"

    - name: Скачиваем и запускаем инсталлятор k3s
      shell: curl -sfL https://get.k3s.io | sh -
      become: true
      args:
        creates: /usr/local/bin/k3s

    - name: Создаем директорию .kube в домашней папке текущего юзера
      file:
        path: "{{ ansible_user_dir }}/.kube"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Копируем конфигурационный файл k3s config под sudo
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ ansible_user_dir }}/.kube/config"
        remote_src: true
        owner: "{{ ansible_user_id }}" 
        group: "{{ ansible_user_id }}"
        mode: '0600'
      become: true

    - name: Настраиваем permanent алиас k='k3s kubectl'
      lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: "alias k='k3s kubectl'"
        state: present

    - name: Скачиваем дебиан-пакет K9s
      get_url:
        url: https://github.com/derailed/k9s/releases/latest/download/k9s_linux_amd64.deb
        dest: /tmp/k9s_linux_amd64.deb
        mode: '0644'

    - name: Устанавливаем K9s через пакетный менеджер apt
      apt:
        deb: /tmp/k9s_linux_amd64.deb
      become: true

    - name: Удаляем временный дебиан-пакет
      file:
        path: /tmp/k9s_linux_amd64.deb
        state: absent






